# Generated by Django 6.0.1 on 2026-01-26 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Notas sobre calidad o tipo', null=True)),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Nota (Rojo)')),
                ('date', models.DateField(verbose_name='Fecha del Recibo')),
                ('client_name', models.CharField(max_length=255, verbose_name='Señor(es)')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Empleado que registra')),
                ('total_weight', models.DecimalField(decimal_places=2, help_text='Suma total de pesos', max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_type', models.CharField(choices=[('KG', 'Kilogramos'), ('PZ', 'Piezas/Unidad')], default='KG', max_length=2)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_manager.material', verbose_name='Material (Seleccionar)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports_manager.ticket')),
            ],
        ),
    ]
