# Generated by Django 6.0.1 on 2026-03-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0002_provider_address_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_id_number', models.CharField(max_length=20)),
                ('rumpa_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_brand', models.CharField(max_length=50)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_plate', models.CharField(max_length=20)),
                ('truck_color', models.CharField(max_length=20)),
                ('start_address', models.CharField(max_length=200)),
                ('start_city', models.CharField(max_length=100)),
                ('start_state', models.CharField(max_length=100)),
                ('end_address', models.CharField(max_length=200)),
                ('end_city', models.CharField(max_length=100)),
                ('end_state', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.provider')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.ticket')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_brand', models.CharField(max_length=50)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_plate', models.CharField(max_length=20)),
                ('truck_color', models.CharField(max_length=20)),
                ('start_address', models.CharField(max_length=200)),
                ('start_city', models.CharField(max_length=100)),
                ('start_state', models.CharField(max_length=100)),
                ('end_address', models.CharField(max_length=200)),
                ('end_city', models.CharField(max_length=100)),
                ('end_state', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.provider')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('inpection_record_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_manager.ticket')),
            ],
        ),
    ]
