# Generated by Django 6.0.1 on 2026-03-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0003_company_affidavit_deliverynote_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reports_manager.provider', verbose_name='Proveedor'),
        ),
    ]
