# Generated by Django 6.0.1 on 2026-03-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0004_remove_ticket_client_name_ticket_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='inpection_record_number',
            new_name='inspection_record_number',
        ),
    ]
