# Generated by Django 6.0.1 on 2026-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0005_rename_inpection_record_number_guide_inspection_record_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
