# Generated by Django 6.0.1 on 2026-04-23 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0006_originaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_note_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Número de Nota de Entrega'),
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_type', models.CharField(choices=[('KG', 'Kilogramos'), ('PZ', 'Piezas/Unidad')], default='KG', max_length=2)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports_manager.deliverynote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_manager.material', verbose_name='Material (Seleccionar)')),
            ],
        ),
    ]
