# Generated by Django 6.0.1 on 2026-04-29 14:51

import reports_manager.models.provider
import reports_manager.models.ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0007_deliverynote_delivery_note_number_deliverynoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=reports_manager.models.provider.Provider.provider_signature_path),
        ),
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=reports_manager.models.ticket.Ticket.ticket_photo_path),
        ),
    ]
