# Generated by Django 6.0.1 on 2026-05-01 15:21

import django.db.models.deletion
import reports_manager.models.vehicle
import reports_manager.models.vehicle_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0009_alter_deliverynote_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_plate_photo',
            field=models.ImageField(blank=True, null=True, upload_to=reports_manager.models.vehicle.Vehicle.license_plate_photo_path),
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports_manager.models.vehicle_photo.VehiclePhoto.vehicle_photos_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports_manager.vehicle')),
            ],
        ),
    ]
