# Generated by Django 6.0.1 on 2026-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_manager', '0010_vehicle_license_plate_photo_vehiclephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
