from .material import Material
from .ticket import Ticket
from .ticket_item import TicketItem
from .provider import Provider
from .vehicle import Vehicle
from .address import Address
from .company import Company
from .guide import Guide
from .affidavit import Affidavit
from .delivery_notes import DeliveryNote
from .origin_address import OriginAddress   
from .delivery_note_item import DeliveryNoteItem
from .vehicle_photo import VehiclePhoto
