from .vehicle import VehicleViewSet
from .address import AddressViewSet
from .affidavit import AffidavitViewSet
from .company import CompanyViewSet
from .delivery_note import DeliveryNoteViewSet
from .guide import GuideViewSet
from .material import MaterialViewSet
from .provider import ProviderViewSet
from .ticket import TicketViewSet
from .ticket_item import TicketItemViewSet