from .vehicle import VehicleSerializer
from .address import AddressSerializer
from .affidavit import AffidavitSerializer
from .company import CompanySerializer
from .delivery_note import DeliveryNoteSerializer
from .guide import GuideSerializer
from .material import MaterialSerializer
from .provider import ProviderSerializer
from .ticket import TicketSerializer
from .ticket_item import TicketItemSerializer
