
export const Words_diccionary: Record<string, string> = {
address: 'Dirección',
city: 'Ciudad',
state: 'Estado',
provider: 'Proveedor',
company: 'Empresa',
ticket: 'Ticket',
truck_brand: 'Marca del Camión',
truck_model: 'Modelo del Camión',
truck_color: 'Color del Camión',
truck_plate: 'Placa del Camión',
start_address: 'Dirección de Inicio',
end_address: 'Dirección de Destino',
start_city: 'Ciudad de Inicio',
end_city: 'Ciudad de Destino',
start_state: 'Estado de Inicio',
end_state: 'Estado de Destino',
creation_date: 'Fecha de Creación',
startdate: 'Fecha de Inicio',
enddate: 'Fecha de Fin',
name: 'Nombre',
company_id_number: "RIF",
rumpa_code: 'Código Rumpa',
status: 'Estado',
date: 'Fecha',
inspection_record_number: 'Número de Registro de Inspección',
description: 'Descripción',
id_number: "Número de Cédula",
report: 'Reporte',
material: 'Material',
amount: 'Cantidad',
unit_type: 'Tipo de Unidad',
ticket_number: 'Número de Ticket',
client_name: 'Nombre del Cliente',
employee_name: 'Nombre del Empleado',
total_weight: 'Peso Total',
installment_amount: 'Monto de la Cuota',
id: 'ID',
brand: 'Marca',
model: 'Modelo',
color: 'Color',
plate: 'Placa',
is_main: 'Es Principal',
providers: 'Proveedores',
addresses: 'Direcciones',
vehicles: 'Vehículos',
guides: 'Guías',
affidavits: 'Declaraciones Juradas',
delivery_notes: 'Notas de Entrega',
vehicle: 'Vehículo',
guide: 'Guía',
affidavit: 'Declaración Jurada',
delivery_note: 'Nota de Entrega',
ticket_display: 'Ticket',

};